### ISSUE TITLE
Need to improve Javadoc for Algorithmia API, can change class names

### ISSUE THREAD

**Issue by gansai** [algorithmiaio/support#1]
https://algorithmia.com/assets/doc/java/algorithmia/api/APIException.html
In class APIException, the javadoc says:
AlgorithmiaException indicates a problem communicating with Algorithmia

This has to be changed to indicate APIException.

And moreover, APIException can be renamed to APICommunicationException if that is the intention of this exception.

**Comment by Argoday** [comment]
Fix commit pushed - pending deployment

**Comment by Argoday** [comment]
Fix deployed awhile ago
